---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: cluster-certificate
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.0.0"
    values.chart.helm.kubeaddons.mesosphere.io/cluster-certificate: "https://github.com/Ganasagar/konvoy-cluster-certs.git/master/charts/cluster-certificate/values.yaml"
spec:
  namespace: kubeaddons
  kubernetes: 
    minSupportedVersion: v1.15.6
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: cert-manager
  chartReference:
    chart: cluster-certificate
    repo: https://github.com/Ganasagar/konvoy-cluster-certs
    version: 1.0.0
    
